name: "Project Status Manager"
description: "Manages GitHub Project V2 item status (add to project, update status)"

inputs:
  action:
    description: "Action to perform: add-to-project | update-status"
    required: true
  issue-node-id:
    description: "Node ID of the issue/PR to manage"
    required: true
  target-status:
    description: "Target status name (Backlog, Progress, Review)"
    required: false
    default: ""
  project-number:
    description: "GitHub Project number"
    required: true
  owner-type:
    description: "Owner type: user | organization"
    required: false
    default: "user"
  status-field-name:
    description: "Status field name in the project"
    required: false
    default: "Status"
  max-pages:
    description: "Maximum pages to search for item"
    required: false
    default: "10"
  github-token:
    description: "GitHub token with project permissions"
    required: true

outputs:
  item-id:
    description: "The project item ID"
    value: ${{ steps.result.outputs.item_id }}
  success:
    description: "Whether the action succeeded"
    value: ${{ steps.result.outputs.success }}

runs:
  using: "composite"
  steps:
    - name: Get project data
      id: project
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        OWNER: ${{ github.repository_owner }}
        PROJECT_NUMBER: ${{ inputs.project-number }}
        STATUS_FIELD_NAME: ${{ inputs.status-field-name }}
        OWNER_TYPE: ${{ inputs.owner-type }}
      run: |
        RESULT=$("${{ github.action_path }}/scripts/get-project-data.sh" \
          "$OWNER" \
          "$PROJECT_NUMBER" \
          "$STATUS_FIELD_NAME" \
          "$OWNER_TYPE")

        PROJECT_ID=$(echo "$RESULT" | grep "^project_id=" | cut -d= -f2-)
        STATUS_FIELD_ID=$(echo "$RESULT" | grep "^status_field_id=" | cut -d= -f2-)
        STATUS_OPTIONS=$(echo "$RESULT" | grep "^status_options=" | cut -d= -f2-)

        echo "project_id=$PROJECT_ID" >> $GITHUB_OUTPUT
        echo "status_field_id=$STATUS_FIELD_ID" >> $GITHUB_OUTPUT
        echo "status_options=$STATUS_OPTIONS" >> $GITHUB_OUTPUT

    - name: Resolve target option ID
      id: option
      if: inputs.target-status != ''
      shell: bash
      env:
        TARGET_STATUS: ${{ inputs.target-status }}
        STATUS_OPTIONS: ${{ steps.project.outputs.status_options }}
      run: |
        OPTIONS="$STATUS_OPTIONS"
        TARGET="$TARGET_STATUS"
        OPTION_ID=$(echo "$OPTIONS" | jq -r --arg name "$TARGET" '.[] | select(.name == $name) | .id')

        if [ -z "$OPTION_ID" ] || [ "$OPTION_ID" = "null" ]; then
          echo "::error::Status option '$TARGET' not found in project"
          exit 1
        fi

        echo "option_id=$OPTION_ID" >> $GITHUB_OUTPUT

    - name: Add to project
      id: add
      if: inputs.action == 'add-to-project'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        PROJECT_ID: ${{ steps.project.outputs.project_id }}
        CONTENT_ID: ${{ inputs.issue-node-id }}
      run: |
        ITEM_ID=$(gh api graphql -f query='
          mutation($projectId: ID!, $contentId: ID!) {
            addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
              item { id }
            }
          }
        ' -f projectId="$PROJECT_ID" \
          -f contentId="$CONTENT_ID" | jq -r '.data.addProjectV2ItemById.item.id')

        if [ -z "$ITEM_ID" ] || [ "$ITEM_ID" = "null" ]; then
          echo "::error::Failed to add item to project"
          exit 1
        fi

        echo "item_id=$ITEM_ID" >> $GITHUB_OUTPUT

    - name: Find existing item
      id: find
      if: inputs.action == 'update-status'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        PROJECT_ID: ${{ steps.project.outputs.project_id }}
        CONTENT_ID: ${{ inputs.issue-node-id }}
        MAX_PAGES: ${{ inputs.max-pages }}
      run: |
        RESULT=$("${{ github.action_path }}/scripts/find-project-item.sh" \
          "$PROJECT_ID" \
          "$CONTENT_ID" \
          "$MAX_PAGES")

        ITEM_ID=$(echo "$RESULT" | grep "^item_id=" | cut -d= -f2-)

        if [ -z "$ITEM_ID" ]; then
          echo "::error::Item not found in project"
          exit 1
        fi

        echo "item_id=$ITEM_ID" >> $GITHUB_OUTPUT

    - name: Update status
      id: update
      if: inputs.action == 'update-status' && steps.find.outputs.item_id != ''
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        "${{ github.action_path }}/scripts/update-item-status.sh" \
          "${{ steps.project.outputs.project_id }}" \
          "${{ steps.find.outputs.item_id }}" \
          "${{ steps.project.outputs.status_field_id }}" \
          "${{ steps.option.outputs.option_id }}"

    - name: Update status after add
      id: update-after-add
      if: inputs.action == 'add-to-project' && inputs.target-status != ''
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        "${{ github.action_path }}/scripts/update-item-status.sh" \
          "${{ steps.project.outputs.project_id }}" \
          "${{ steps.add.outputs.item_id }}" \
          "${{ steps.project.outputs.status_field_id }}" \
          "${{ steps.option.outputs.option_id }}"

    - name: Set outputs
      id: result
      shell: bash
      env:
        ACTION_TYPE: ${{ inputs.action }}
        ADD_ITEM_ID: ${{ steps.add.outputs.item_id }}
        FIND_ITEM_ID: ${{ steps.find.outputs.item_id }}
        ADD_OUTCOME: ${{ steps.add.outcome }}
        UPDATE_OUTCOME: ${{ steps.update.outcome }}
      run: |
        if [ "$ACTION_TYPE" = "add-to-project" ]; then
          echo "item_id=$ADD_ITEM_ID" >> $GITHUB_OUTPUT
          if [ "$ADD_OUTCOME" = "success" ]; then
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "success=false" >> $GITHUB_OUTPUT
          fi
        else
          echo "item_id=$FIND_ITEM_ID" >> $GITHUB_OUTPUT
          if [ "$UPDATE_OUTCOME" = "success" ]; then
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "success=false" >> $GITHUB_OUTPUT
          fi
        fi
